version: "3.9"

services:
  fastapi:
    build: .
    environment:
      - REDIS_HOST=redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always